name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Changez cela en fonction de votre branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Checkout du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2: Configurer Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Utilisez la version Node.js que vous utilisez

    # Étape 3: Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4: Exécuter les tests
    - name: Run tests
      run: npm test

    # Étape 5: Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t my-node-app .

    # Étape 6: Pousser l'image Docker vers Docker Hub
    - name: Push Docker image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.jordama }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.dckr_pat_9zKFT4vXweqfzGWBrcUcZ6__Mho }}
      run: |
        echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        docker tag my-node-app $DOCKER_HUB_USERNAME/my-node-app:latest
        docker push $DOCKER_HUB_USERNAME/my-node-app:latest

    # Étape 7: Déployer l'image (optionnel)
    - name: Deploy to server
      run: |
        echo "Deploying to server..."
        # Ajoutez les commandes spécifiques à votre plateforme de déploiement ici.
